;; agent/tests/anatta-log-tests.el
(require 'ert)
(require 'anatta-log)

(ert-deftest anatta-log-append-is-tail-ordered ()
  (let ((anatta-log nil))
    (anatta-log-append (list :role 'user :content "first"))
    (anatta-log-append (list :role 'user :content "second"))
    (should (equal (plist-get (car anatta-log) :content) "first"))
    (should (equal (plist-get (cadr anatta-log) :content) "second"))))

(ert-deftest anatta-log-to-provider-messages-folds-roles ()
  (let ((log (list (list :role 'user :content "do it")
                    (list :role 'assistant :code "(+ 1 2)")
                    (list :role 'result :value "3")
                    (list :role 'result :error "boom"))))
    (let ((msgs (anatta-log-to-provider-messages log)))
      (should (equal (plist-get (nth 0 msgs) :role) "user"))
      (should (equal (plist-get (nth 0 msgs) :content) "do it"))
      (should (equal (plist-get (nth 1 msgs) :role) "assistant"))
      (should (equal (plist-get (nth 1 msgs) :content) "```elisp\n(+ 1 2)\n```"))
      (should (equal (plist-get (nth 2 msgs) :role) "user"))
      (should (equal (plist-get (nth 2 msgs) :content) "Eval result: 3"))
      (should (equal (plist-get (nth 3 msgs) :role) "user"))
      (should (equal (plist-get (nth 3 msgs) :content) "Eval error: boom")))))

(ert-deftest anatta-log-persist-and-load-round-trip ()
  (let* ((tmpdir (make-temp-file "anatta-log-test" t))
         (anatta-agent-dir tmpdir))
    (call-process "git" nil nil nil "init" "-q" tmpdir)
    (let ((anatta-log (list (list :role 'user :content "hello"))))
      (anatta-log-persist))
    (let ((anatta-log nil))
      (anatta-log-load)
      (should (equal (plist-get (car anatta-log) :content) "hello")))))

(ert-deftest anatta-log-load-seeds-when-no-file-present ()
  (let* ((tmpdir (make-temp-file "anatta-log-test" t))
         (anatta-agent-dir tmpdir)
         (anatta-log nil))
    (anatta-log-load "the initial task")
    (should (equal (plist-get (car anatta-log) :content) "the initial task"))))
