;; agent/tests/anatta-providers-tests.el
(require 'ert)
(require 'anatta-providers)

(ert-deftest anatta-anthropic-headers ()
  (let ((headers (funcall (plist-get anatta-provider-anthropic :headers-fn) "sk-test")))
    (should (equal (cdr (assoc "x-api-key" headers)) "sk-test"))
    (should (equal (cdr (assoc "anthropic-version" headers)) "2023-06-01"))
    (should (equal (cdr (assoc "content-type" headers)) "application/json"))))

(ert-deftest anatta-anthropic-build-request-shape ()
  (let* ((messages (list (list :role "user" :content "hi")))
         (body (funcall (plist-get anatta-provider-anthropic :build-request)
                         messages "sys prompt" anatta-provider-anthropic))
         (parsed (json-parse-string body :object-type 'alist)))
    (should (equal (alist-get 'system parsed) "sys prompt"))
    (should (equal (alist-get 'model parsed) (plist-get anatta-provider-anthropic :model)))
    (should (equal (alist-get 'role (aref (alist-get 'messages parsed) 0)) "user"))
    (should (equal (alist-get 'content (aref (alist-get 'messages parsed) 0)) "hi"))))

(ert-deftest anatta-anthropic-parse-response-extracts-text ()
  (let ((response "{\"content\":[{\"type\":\"text\",\"text\":\"(+ 1 2)\"}]}"))
    (should (equal (funcall (plist-get anatta-provider-anthropic :parse-response) response)
                    "(+ 1 2)"))))

(ert-deftest anatta-openai-headers ()
  (let ((headers (funcall (plist-get anatta-provider-openai :headers-fn) "sk-test")))
    (should (equal (cdr (assoc "Authorization" headers)) "Bearer sk-test"))
    (should (equal (cdr (assoc "content-type" headers)) "application/json"))))

(ert-deftest anatta-openai-build-request-shape ()
  (let* ((messages (list (list :role "user" :content "hi")))
         (body (funcall (plist-get anatta-provider-openai :build-request)
                         messages "sys prompt" anatta-provider-openai))
         (parsed (json-parse-string body :object-type 'alist))
         (msgs (alist-get 'messages parsed)))
    (should (equal (alist-get 'role (aref msgs 0)) "system"))
    (should (equal (alist-get 'content (aref msgs 0)) "sys prompt"))
    (should (equal (alist-get 'role (aref msgs 1)) "user"))
    (should (equal (alist-get 'content (aref msgs 1)) "hi"))))

(ert-deftest anatta-openai-parse-response-extracts-text ()
  (let ((response "{\"choices\":[{\"message\":{\"role\":\"assistant\",\"content\":\"(+ 1 2)\"}}]}"))
    (should (equal (funcall (plist-get anatta-provider-openai :parse-response) response)
                    "(+ 1 2)"))))
